#!/bin/bash

BASEDIR="$(dirname $0)"

if [ ! -f "$BASEDIR/adam_ui.jar" ] ; then
	echo "adam_ui.jar not found! Run 'ant jar' first!" >&2
	exit 127
fi

java -Dlibfolder=../../lib/ -jar "$BASEDIR/adam_ui.jar" $@
