${mainfolder}/tools/classes
${mainfolder}/petrinetWithTransits/classes
${mainfolder}/logics/classes
${mainfolder}/modelchecking/classes
${mainfolder}/ui/classes
${mainfolder}/adammc/classes
${mainfolder}/petriGames/classes
${mainfolder}/highLevel/classes
${mainfolder}/symbolicalgorithms/bddapproach/classes
${mainfolder}/symbolicalgorithms/mtbddapproach/classes
${mainfolder}/boundedalgorithms/classes
${mainfolder}/adamsynt/classes
${libfolder}/commons-io-2.4/commons-io-2.4.jar
${libfolder}/apt/apt4adam.jar
${libfolder}/commons-collections4-4.0/commons-collections4-4.0.jar
${libfolder}/commons-cli-1.2/commons-cli-1.2.jar
${libfolder}/antlr-4.5.1/antlr-4.5.1-complete.jar
${libfolder}/javaBDD/javabdd-1.0b2.jar
${libfolder}/trove-3.0.3/trove-3.0.3.jar
